# Generated by Django 2.1.7 on 2019-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclass',
            name='name',
            field=models.CharField(default='noname', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageclass',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
